version: '3.8'

services:
  backend-app:
    image: leasing/app:latest
    build:
      context: .
    container_name: leasing-app
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://leasing-db:5432/leasing_database
      - SPRING_FLYWAY_URL=jdbc:postgresql://leasing-db:5432/leasing_database
      - SPRING_PROFILES_ACTIVE=${PROFILE}
    ports:
      - "8080:8080"

  postgres:
    image: postgres:latest
    container_name: leasing-db
    environment:
      POSTGRES_DB: leasing_database
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: